### ISSUE TITLE
Shows night time as sunny

### ISSUE THREAD

**Issue by mpekgit** [anand-p-r/fmi-hass-custom#55]
Currently shows weather as sunny even at night time. Is this something that is fixable?

**Comment by FunctionalHacker** [comment]
Probably because it seems not to be available from the FMI API https://github.com/anand-p-r/fmi-hass-custom/blob/6f9f9a33a774fe10594b320a90692449f795ff23/const.py#L74

One of these days, if I find the time, I can learn more about the API capabilities. Hopefully I can find a way around this so I can submit a PR.

**Comment by cruwaller** [comment]
Yeah, just debugged this a bit and looks like the API returns a bit different symbols as well. 
Close this now.
